NaviyaOrganization/Naviya

- src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
- src/main/java/com/mycom/myapp/naviya/domain/book/dto/BookDetailDto.java
- src/main/java/com/mycom/myapp/naviya/domain/book/dto/BookResultDto.java
- src/main/java/com/mycom/myapp/naviya/domain/book/entity/Book.java
- src/main/java/com/mycom/myapp/naviya/domain/book/repository/BookRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookSerive.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/child/entity/Child.java
- src/main/java/com/mycom/myapp/naviya/domain/child/entity/ChildBookLike.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildBookLikeRepository.java
- src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
Feat_adj_book_dislkie-> dev
book detail  쿼리 변경,도서 쿼리들 나이대별로 들고오게 수정,좋아요 논리적 삭제 구현,좋아요-도서 관계 수정
좋아요 테이블 - 북 테이블에서 일대일 주인이 북에 있으니 좋아요에서 기본키가 있어도
북에 대한 유니크 값도 같이 걸리는 문제가 있었다.
manytoone으로 수정하여 해결
> [Feat]book detail 변경,도서 쿼리들 나이대별로 들고오게 수정,좋아요 논리적 삭제 구현,좋아요-도서 관계 수정

- src/main/java/com/mycom/myapp/naviya/domain/book/service/MbtiRecommendServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
- src/main/resources/templates/childPage.html
- src/main/resources/templates/index.html
- src/main/resources/templates/search.html
feat/mbti_recommend -> dev
index.html 과 search.html 을 타임리프와 연결할 수 있게 변환
sessionStorage에 type을 넣어 어떤 추천으로 넘어왔는 지 저장
ChildMbti 의 연관 관계 설정에 따른 MbtiRecommendServiceImpl 설정
> [feat] index.html 과 search.html 보완

- src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
- src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
- src/main/resources/static/assets/css/newSidebar.css
- src/main/resources/static/assets/js/newSidebar.js
- src/main/resources/static/newNavtoggle.html
- src/main/resources/templates/admin.html
- src/main/resources/templates/adminSignup.html
- src/main/resources/templates/childAdd.html
- src/main/resources/templates/childPage.html
- src/main/resources/templates/childSelectPage.html
- src/main/resources/templates/childUpdate.html
- src/main/resources/templates/login.html
- src/main/resources/templates/signup.html
- src/main/resources/templates/userPage.html
ex) feat/njm_front -> dev
로그인, 회원가입, 네브바, 토글바, 유저페이지, 자녀페이지 프론트 UI 수정했습니다
> [FEATURE] 유저/자녀 페이지 UI 수정

- build.gradle
- src/load-tests/serialtest.js
- src/load-tests/traffictest.js
- src/main/java/com/mycom/myapp/naviya/domain/lottery/controller/LotteryController.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/service/HashLotteryService.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/service/ListLotteryService.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/service/LuaAndQueueLotteryService.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/service/LuaLotteryService.java
ex) 56-enhancement) -> dev
- 서비스 로직 hash 구조로 변경
- 대규모 트래픽 테스트
- 시나리오 작성
- 여러 번의 테스트
- 최적화
추후 블로그 작성 후 첨부 예정
> [FEATURE] #56 대규모 응모 시스템 테스트 및 최적화  

- src/load-tests/serialtest.js
- src/load-tests/traffictest.js
- src/main/java/com/mycom/myapp/naviya/domain/lottery/controller/LotteryController.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/dto/LotteryEntryRequest.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/entity/LotteryEntry.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/service/HashLotteryService.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/service/ListLotteryService.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/service/LuaAndQueueLotteryService.java
- src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
- src/main/resources/templates/lotteryForm.html
- src/main/resources/templates/lotteryResult.html
62-feat -> dev
- 응모 이벤트 페이지에 프론트 부분 모두 구현
- 자녀 성향을 반영한 체험형 프로그램을 선택하는 기능을 추가 # 관련 코드 모두 수정
> [FEATURE] #62 응모 이벤트 페이지 디자인, 체험형 프로그램 기능 추가

- src/main/java/com/mycom/myapp/naviya/domain/book/service/MbtiRecommendServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildMbtiController.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildMbtiRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildMbtiService.java
- src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildMbtiServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/lottery/service/LuaLotteryService.java
- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
- src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
- src/main/resources/templates/index.html
- src/main/resources/templates/search.html
feat/mbti_recommend -> dev
- 메인 페이지, 검색 페이지 css 보완
- 회원, 진단 안한 회원, 비회원 필터링
- mbti 별 추천 로직 보완
- 자녀의 mbti 확인 기능 구현
> [FEATURE] 메인, 검색 페이지 css 보완 및 자녀 mbti 확인 기능

- src/main/java/com/mycom/myapp/naviya/domain/book/repository/BookRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/child/entity/ChildMbti.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildMbtiRepository.java
- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
- src/main/java/com/mycom/myapp/naviya/global/redies/RedisStreamInitializer.java
- src/main/resources/templates/BookCategoryHtml.html
- src/main/resources/templates/ChildFavorBookList.html
- src/main/resources/templates/ChildRecentReadBook.html
- src/main/resources/templates/index.html
temp adjuset-> dev
다시 pr을 위한 수정
프론트 매핑 수정 
첫 생성시 레디스 스트림 생성 추가 
> Feat temp adjuset

- src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
- src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildMbtiController.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildService.java
- src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildServiceImpl.java
> 카테고리 존재 확인 api 추가

- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildMbtiController.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildService.java
- src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildServiceImpl.java
> Feat add category chek

- src/main/resources/static/assets/css/newSidebar.css
- src/main/resources/static/newNavtoggle.html
- src/main/resources/templates/BookReadPage.html
- src/main/resources/templates/ChildFavorBookList.html
- src/main/resources/templates/ChildRecentReadBook.html
- src/main/resources/templates/childAdd.html
- src/main/resources/templates/childAddAskMbti.html
- src/main/resources/templates/childMBTIResult.html
- src/main/resources/templates/childPage.html
- src/main/resources/templates/childSelectPage.html
- src/main/resources/templates/childUpdate.html
- src/main/resources/templates/diagnosisForm.html
- src/main/resources/templates/login.html
- src/main/resources/templates/lotteryForm.html
- src/main/resources/templates/mbtiHistory.html
- src/main/resources/templates/search.html
- src/main/resources/templates/signup.html
- src/main/resources/templates/userPage.html
ex) feat/test60 -> dev
side바, font 수정했습니다
> [Feature] sidebar, font 수정

- build.gradle
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/child/entity/Child.java
- src/main/java/com/mycom/myapp/naviya/global/mbti/entity/Mbti.java
- src/main/resources/static/assets/js/newSidebar.js
- src/main/resources/templates/index.html
- src/main/resources/templates/search.html
feat/mbti_recommend -> dev
카테고리 별 책 추천 추가
메인 페이지, 검색 페이지 움직이는 버그 수정 
> [FEATURE] 메인, 검색 페이지 보완

- build.gradle
- src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookAiController.java
- src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
- src/main/java/com/mycom/myapp/naviya/domain/book/dto/BookDetailDto.java
- src/main/java/com/mycom/myapp/naviya/domain/book/dto/BookDto.java
- src/main/java/com/mycom/myapp/naviya/domain/book/dto/BookInsertDto.java
- src/main/java/com/mycom/myapp/naviya/domain/book/entity/Book.java
- src/main/java/com/mycom/myapp/naviya/domain/book/repository/BookRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookAiServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookService.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildMbtiRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildRepository.java
- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
- src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
- src/main/resources/templates/AdminBookDetailPage.html
- src/main/resources/templates/BookDetailPage.html
- src/main/resources/templates/BookInsertPage.html
- src/main/resources/templates/BookReadPage.html
- src/main/resources/templates/admin.html
> [FEATURE] 관리자 기능 추가, 책 상세보기, 오디오북 수정

- src/main/resources/templates/index.html
feat-mbti_recommend -> dev
메인 페이지 카테고리 별 책 추천 수정 
> [FEATURE] 메인 페이지 카테고리 별 책 추천 수정

- src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
- src/main/resources/templates/BookCategoryHtml.html
- src/main/resources/templates/ChildFavorBookList.html
- src/main/resources/templates/ChildRecentReadBook.html
- src/main/resources/templates/childSelectPage.html
> Feat front adjuset

- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookAiServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
- src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
- src/main/resources/templates/BookCategoryHtml.html
- src/main/resources/templates/BookDetailPage.html
- src/main/resources/templates/BookInsertPage.html
- src/main/resources/templates/BookReadPage.html
- src/main/resources/templates/ChildFavorBookList.html
- src/main/resources/templates/ChildRecentReadBook.html
- src/main/resources/templates/admin.html
- src/main/resources/templates/childMBTIResult.html
- src/main/resources/templates/diagnosisForm.html
- src/main/resources/templates/index.html
- src/main/resources/templates/lotteryForm.html
- src/main/resources/templates/lotteryResult.html
- src/main/resources/templates/mbtiHistory.html
- src/main/resources/templates/search.html
- src/main/resources/templates/signup.html
ex) feat/test60 -> dev
전체적인 프론트 수정
> [Feat] 프론트 전체 수정1

- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
- src/main/resources/static/assets/css/newSidebar.css
- src/main/resources/templates/BookCategoryHtml.html
- src/main/resources/templates/ChildFavorBookList.html
- src/main/resources/templates/index.html
- src/main/resources/templates/search.html
> [Feature] 메인 프론트 수정2

- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/LikeDislikeProcessor.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildBookDisLikeRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildBookLikeRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
> [feat] 프론트 수정/*-`1234567890

- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookAiServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildMbtiRepository.java
- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
- src/main/resources/static/assets/css/newSidebar.css
- src/main/resources/templates/BookCategoryHtml.html
- src/main/resources/templates/ChildRecentReadBook.html
- src/main/resources/templates/admin.html
- src/main/resources/templates/lotteryForm.html
> [Feature] 프론트 수정

- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
- src/main/resources/templates/index.html
> [Feature] 프론트수정

- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/LikeDislikeProcessor.java
- src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildFavorCategoryDto.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
- src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
- src/main/resources/templates/BookDetailPage.html
> [feat] 백엔드 카테고리 오류 수정

- src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
- src/main/java/com/mycom/myapp/naviya/domain/book/repository/BookRepository.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookService.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/resources/static/allbook.html
- src/main/resources/templates/allbook.html
> [FEATURE] 모든 책 보기 기능 추가

- src/test/java/com/mycom/myapp/naviya/domain/book/service/MbtiRecommendServiceImplTest.java
> [Test] mbti 별 책 추천 테스트 코드

- src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildMbtiServiceImpl.java
- src/test/java/com/mycom/myapp/naviya/domain/child/service/ChildMbtiServiceImplTest.java
ex) feat-ChildMbtiServiceImplTest -> dev
ChildMbtiServiceImpl 테스트 코드 작성
> [Test] [Feat] ChildMbtiServiceImpl 테스트 코드 작성

- build.gradle
- src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
- src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
- src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildBookLikeRepository.java
- src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookCategoryOneTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookChildFavorList.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookFavoTotalTEST.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookFavorLike.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookFavorService.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookFavorTotalConcurrencyTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookMBTItEST.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImplTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/BookServiceTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/CategoryBookListTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/ChildALLBOOK.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/ChildBookCount.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/ChildBookLIkeDisLikeTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/ChildMbtiDel.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/ChildMbtiServiceImplTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/NoChildBook.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/categoryDisLikeTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/categoryLike.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/categorycrudTest.java
- src/test/java/com/mycom/myapp/naviya/domain/book/service/listbookOrderByCreateDateTest.java
> [feat]테스트 코드 추가 
